// Generated by CoffeeScript 1.4.0
(function() {
  var Alfred, call, fs, path, system, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  fs = require('fs');

  path = require('path');

  _ref = require('./utils'), call = _ref.call, system = _ref.system;

  Alfred = (function() {

    function Alfred(options) {
      var _base, _ref1;
      this.options = options != null ? options : {};
      this.say = __bind(this.say, this);

      this.saveSay = __bind(this.saveSay, this);

      this.sayRandom = __bind(this.sayRandom, this);

      this.saveSayRandom = __bind(this.saveSayRandom, this);

      this._sayRandom = __bind(this._sayRandom, this);

      this.getRandomWordPath = __bind(this.getRandomWordPath, this);

      this.listVoiceWords = __bind(this.listVoiceWords, this);

      this.listWords = __bind(this.listWords, this);

      this.getVoices = __bind(this.getVoices, this);

      this._say = __bind(this._say, this);

      this.getDestFile = __bind(this.getDestFile, this);

      this.getWordPath = __bind(this.getWordPath, this);

      this.getVoicePath = __bind(this.getVoicePath, this);

      this.listVoices = __bind(this.listVoices, this);

      this.getSox = __bind(this.getSox, this);

      if ((_ref1 = (_base = this.options).voicesDirectory) == null) {
        _base.voicesDirectory = path.join(__dirname, '../voices');
      }
      return this;
    }

    Alfred.prototype.getSox = function() {
      return 'sox';
    };

    Alfred.prototype.listVoices = function(fn) {
      return fs.readdir(this.options.voicesDirectory, fn);
    };

    Alfred.prototype.getVoicePath = function(voice) {
      return path.join(this.options.voicesDirectory, voice);
    };

    Alfred.prototype.getWordPath = function(word, voice) {
      if (voice == null) {
        voice = null;
      }
      if (voice == null) {
        voice = this.options.voice;
      }
      return path.join(this.options.voicesDirectory, voice, "" + word + ".wav");
    };

    Alfred.prototype.getDestFile = function() {
      return this.options.out || "/tmp/salut-c-est-alfred-ton-banquier.mp3";
    };

    Alfred.prototype._say = function(words, destFile, fn) {
      var cmd,
        _this = this;
      cmd = [this.getSox()];
      return this.getVoices(function(err, voices) {
        var voice, word, _i, _len;
        for (_i = 0, _len = words.length; _i < _len; _i++) {
          word = words[_i];
          voice = voices[Math.floor(voices.length * Math.random())];
          cmd.push(_this.getWordPath(word, voice));
        }
        cmd.push(destFile);
        return fn(false, cmd);
      });
    };

    Alfred.prototype.getVoices = function(fn) {
      if (this.options.voice) {
        return fn(false, [this.options.voice]);
      }
      return this.listVoices(fn);
    };

    Alfred.prototype.listWords = function(fn) {
      var todo, voicesWords,
        _this = this;
      voicesWords = {};
      todo = 0;
      return this.getVoices(function(err, voices) {
        var _i, _len, _results, _voice;
        _results = [];
        for (_i = 0, _len = voices.length; _i < _len; _i++) {
          _voice = voices[_i];
          _results.push((function() {
            var voice;
            voice = _voice;
            voicesWords[voice] = [];
            todo++;
            return _this.listVoiceWords(voice, function(err, words) {
              var word, _j, _len1;
              if (!err) {
                for (_j = 0, _len1 = words.length; _j < _len1; _j++) {
                  word = words[_j];
                  voicesWords[voice].push(word);
                }
              }
              if (!--todo) {
                return fn(false, voicesWords);
              }
            });
          })());
        }
        return _results;
      });
    };

    Alfred.prototype.listVoiceWords = function(voice, fn) {
      var _this = this;
      return fs.readdir(this.getVoicePath(voice), function(err, files) {
        var file, k;
        for (k in files) {
          file = files[k];
          files[k] = files[k].slice(0, +(file.length - 5) + 1 || 9e9);
        }
        return fn(err, files);
      });
    };

    Alfred.prototype.getRandomWordPath = function() {};

    Alfred.prototype._sayRandom = function(length, destFile, fn) {
      var cmd,
        _this = this;
      if (length == null) {
        length = 10;
      }
      if (destFile == null) {
        destFile = null;
      }
      cmd = [this.getSox()];
      return this.listWords(function(err, voiceWords) {
        var i, voice, voices, word, words, _i;
        voices = [
          (function() {
            var _results;
            _results = [];
            for (voice in voiceWords) {
              _results.push(voice);
            }
            return _results;
          })()
        ][0];
        console.log(voices);
        console.log(length);
        for (i = _i = 0; 0 <= length ? _i <= length : _i >= length; i = 0 <= length ? ++_i : --_i) {
          voice = voices[Math.floor(voices.length * Math.random())];
          words = voiceWords[voice];
          word = words[Math.floor(words.length * Math.random())];
          cmd.push(_this.getWordPath(word, voice));
        }
        cmd.push(destFile);
        console.log(cmd);
        return fn(false, cmd);
      });
    };

    Alfred.prototype.saveSayRandom = function(length, destFile, fn) {
      var _this = this;
      if (destFile == null) {
        destFile = null;
      }
      return this._sayRandom(length, destFile, function(err, cmd) {
        var args, bin, _ref1;
        console.log('test');
        _ref1 = [cmd[0], cmd.slice(1)], bin = _ref1[0], args = _ref1[1];
        console.log(bin, args);
        return call(bin, args, function(err, data) {
          console.log("Done. " + destFile);
          return fn(err, data);
        });
      });
    };

    Alfred.prototype.sayRandom = function(length, fn) {
      var destFile,
        _this = this;
      if (fn == null) {
        fn = null;
      }
      destFile = this.getDestFile();
      return this.saveSayRandom(length, destFile, function(err, data) {
        return system('play', [destFile]);
      });
    };

    Alfred.prototype.saveSay = function(words, destFile, fn) {
      var _this = this;
      if (destFile == null) {
        destFile = null;
      }
      return this._say(words, destFile, function(err, cmd) {
        var args, bin, _ref1;
        console.log('test');
        _ref1 = [cmd[0], cmd.slice(1)], bin = _ref1[0], args = _ref1[1];
        console.log(bin, args);
        return call(bin, args, function(err, data) {
          console.log("Done. " + destFile);
          return fn(err, data);
        });
      });
    };

    Alfred.prototype.say = function(words, fn) {
      var destFile,
        _this = this;
      if (fn == null) {
        fn = null;
      }
      destFile = this.getDestFile();
      return this.saveSay(words, destFile, function(err, data) {
        return system('play', [destFile]);
      });
    };

    return Alfred;

  })();

  module.exports = {
    Alfred: Alfred
  };

}).call(this);
