// Generated by CoffeeScript 1.4.0
(function() {
  var Alfred, fs, path,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  fs = require('fs');

  path = require('path');

  Alfred = (function() {

    function Alfred(options) {
      var _base, _ref;
      this.options = options != null ? options : {};
      this.say = __bind(this.say, this);

      this.getWordPath = __bind(this.getWordPath, this);

      this.listVoices = __bind(this.listVoices, this);

      if ((_ref = (_base = this.options).voicesDirectory) == null) {
        _base.voicesDirectory = path.join(__dirname, '../voices');
      }
      return this;
    }

    Alfred.prototype.listVoices = function(fn) {
      return fs.readdir(this.options.voicesDirectory, fn);
    };

    Alfred.prototype.getWordPath = function(word) {
      return path.join(this.options.voicesDirectory, this.options.voice, "" + word + ".wav");
    };

    Alfred.prototype.say = function(words, fn) {
      var word, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = words.length; _i < _len; _i++) {
        word = words[_i];
        _results.push(console.log(this.getWordPath(word)));
      }
      return _results;
    };

    return Alfred;

  })();

  module.exports = {
    Alfred: Alfred
  };

}).call(this);
