// Generated by CoffeeScript 1.4.0
(function() {
  var call, exec, spawn, system, _ref;

  _ref = require('child_process'), spawn = _ref.spawn, exec = _ref.exec;

  call = function(command, args, fn) {
    if (args == null) {
      args = [];
    }
    if (fn == null) {
      fn = null;
    }
    return exec("" + command + " " + (args.join(' ')), function(err, stdout, stderr) {
      if (err != null) {
        console.error("Error :");
        return console.dir(err);
      }
      if (fn) {
        return fn(err);
      }
    });
  };

  system = function(command, args) {
    return spawn(command, args, {
      stdio: "inherit"
    });
  };

  module.exports = {
    call: call,
    system: system
  };

}).call(this);
